### ISSUE TITLE
Check ORF ids are consistent in different data files

### ISSUE THREAD

**Issue by ewallace** [ewallace/cryptowakeup_mscdatasci2020#6]
I think there were some ORF ids inconsistent with different data files!

We should double-check - refer to FungiDB for new versions.

@DimmestP could you take a look?

**Comment by DimmestP** [comment]
There are 1,280 gene ids that are found in the RNAseq data set that do not have an entry in the kmers files. How did you originally select which genes to download from fungiDB? 

Is this what you mean by 'inconsistent'? Or are you suggesting that there are some genes that are given different names in different files? I haven't noticed any evidence for that but also don't really know how I could check for that as there isn't any other  data shared between the files to cross-reference.

**Comment by DimmestP** [comment]
I've redownloaded the fasta files from fungiDB including the missing genes, currently in [my fork](https://github.com/DimmestP/cryptowakeup_mscdatasci2020/tree/master/data) of the repo. Will submit pull request when I've finished calculating the kmers again.

**Comment by ewallace** [comment]
That is what I meant, and I didn't realize it was nearly so many genes.

I think:
* `CNAG_0xxxx` are all the (suspected) protein-coding genes, and should be included
* `CNAG_1xxxx` are all the  non-coding RNA genes, most of them are garbage and should not be included. Also most ncRNA uses a different transcriptional apparatus so is not regulated the same way, thus a different biological question.
* `H99_allorfs_ids.txt` only includes coding genes up to `CNAG_07946`, for reasons lost to the mists of time

I'm sorry, this is truly irritating. The easiest fix would be to 
* replace `H99_allorfs_ids.txt` by a file containing the data for all coding genes, i.e. up to `CNAG_08029`. That would be a few lines of code to extract, see below.
* download new approximate 500nt promoters and 250nt terminators using [FungiDB sequence retrieval tool](https://fungidb.org/fungidb/app/fasta-tool) *on the new list*
* recalculate the k-mers using `CountKMers.Rmd`. But first check with @nataliabochkina if we want something other than 5-mers?

@DimmestP how does that sound?

Those few lines of code:

```
here::here("data","CW-kallisto-abundance-foldchange-long-bygene.txt") %>%
    readr::read_tsv(col_types="ccnn", comment= "#") %>%
    dplyr::pull(Gene) %>%
    unique() %>%
    stringr::str_subset("CNAG_0") %>%
    readr::write_tsv("H99_neworfids_chooseabettername.txt")
```
